"""change name to full_name student and teacher table

Revision ID: 2c37d65b5f68
Revises: 6c7d4248a376
Create Date: 2025-03-24 13:04:17.830815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2c37d65b5f68'
down_revision: Union[str, None] = '6c7d4248a376'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('full_name', sa.String(length=50), nullable=False))
    op.drop_column('students', 'name')
    op.add_column('subjects', sa.Column('title', sa.String(length=50), nullable=False))
    op.drop_column('subjects', 'name')
    op.add_column('teachers', sa.Column('full_name', sa.String(length=50), nullable=False))
    op.drop_column('teachers', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('teachers', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('teachers', 'full_name')
    op.add_column('subjects', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('subjects', 'title')
    op.add_column('students', sa.Column('name', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_column('students', 'full_name')
    # ### end Alembic commands ###
